### ISSUE TITLE
Incorrect character rendering on webpage - displaying "&quot; and "#039s;" instead of symbols

### ISSUE THREAD

**Issue by DheerajRay-01** [ritiku2004/Quick-Quize#1]
## I encountered an issue on your webpage where certain symbols are not displaying correctly. Instead of the intended symbols, I see "&quot;" and "#039s;". This seems to be an issue with character encoding.

# Expected behavior:
The webpage should render all symbols correctly.

# Actual behavior:
Symbols are replaced with "&quot;" and "#039s;".

# Additional information:
1. Browser  used - Chrome , Firefox 
2. Operating system - Linux &  Windows 10

# ScreenShot
![Screenshot from 2024-07-09 15-57-07](https://github.com/ritiku2004/Quick-Quize/assets/144889143/a3d18148-5f8c-46d3-8f27-af11fddbf7cc)

I hope this helps!

**Comment by ritiku2004** [comment]
Can you work on it ?

**Comment by DheerajRay-01** [comment]
yes ! 
I will send you PR after correct this issue
